# Generated by Django 4.1.3 on 2023-01-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mimetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entero1', models.PositiveIntegerField(default=0)),
                ('entero2', models.PositiveIntegerField(default=0)),
                ('entero3', models.PositiveIntegerField(default=0)),
                ('texto1', models.CharField(blank=True, max_length=100, null=True)),
                ('texto2', models.CharField(blank=True, max_length=100, null=True)),
                ('texto3', models.CharField(blank=True, max_length=100, null=True)),
                ('importe1', models.FloatField(blank=True)),
                ('importe2', models.FloatField(blank=True)),
                ('importe3', models.FloatField(blank=True)),
                ('check1', models.BooleanField(blank=True)),
                ('check2', models.BooleanField(blank=True)),
                ('check3', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('size', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to='files')),
                ('mimetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basics.mimetype')),
            ],
        ),
    ]
