# Generated by Django 4.1.3 on 2023-01-01 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import marketplace.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen_ref', models.ImageField(blank=True, null=True, upload_to=marketplace.models.user_directory_path)),
                ('precio_avg', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen_ref', models.ImageField(blank=True, null=True, upload_to='categories/images')),
                ('icon_ref', models.ImageField(blank=True, null=True, upload_to='categories/icons')),
            ],
        ),
        migrations.CreateModel(
            name='MapMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=18)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=18)),
                ('type', models.CharField(max_length=2)),
                ('instance_id', models.PositiveBigIntegerField(null=True)),
                ('icon_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basics.file')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen_ref', models.ImageField(blank=True, null=True, upload_to=marketplace.models.user_directory_path)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_ori', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('base_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.baseproducto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.categoria')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('map_mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.mapmark')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baseproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.categoria'),
        ),
        migrations.AddField(
            model_name='baseproducto',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
