# Generated by Django 4.1.3 on 2022-12-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_ref',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
